# Tributo
ENERGIA_ACCION_HEROICA = 20
POPULARIDAD_ACCION_HEROICA = 30
ENERGIA_ATACAR = 15
POPULARIDAD_ATACAR = 20
POPULARIDAD_PEDIR = 15
ENERGIA_BOLITA = 10
COSTO_OBJETO = 20
VIDA_MAX = 100
ENERGIA_MAX = 100
VIDA_MIN = 0
ENERGIA_MIN = 0

# Ambiente Playa
VELOCIDAD_VIENTOS_PLAYA = 10
HUMEDAD_PLAYA = 15

# Ambiente Montana
NUBOSIDAD_MONTANA = 10
PRECIPITACIONES_MONTANA = 25

# Ambiente Bosque
PRECIPITACIONES_BOSQUE = 20
VELOCIDAD_VIENTOS_BOSQUE = 10

# Objeto Consumible
AUMENTAR_ENERGIA = 20

# Objeto Arma
PONDERADOR_AUMENTAR_FUERZA = 20

# Objeto Especial
AUMENTAR_AGILIDAD = 20
AUMENTAR_INGENIO = 20

# Arena
PROBABILIDAD_EVENTO = 0.6  # float entre 0 y 1
